/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StravaCallbackRouteImport } from './routes/strava/callback'
import { Route as StravaLoginRouteImport } from './routes/strava/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StravaCallbackRoute = StravaCallbackRouteImport.update({
  id: '/strava/callback',
  path: '/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const StravaLoginRoute = StravaLoginRouteImport.update({
  id: '/strava/login',
  path: '/strava/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/strava/login': typeof StravaLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/strava/login': typeof StravaLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/strava/login': typeof StravaLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/strava/callback' | '/strava/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/strava/callback' | '/strava/login'
  id: '__root__' | '/' | '/strava/callback' | '/strava/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StravaCallbackRoute: typeof StravaCallbackRoute
  StravaLoginRoute: typeof StravaLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strava/callback': {
      id: '/strava/callback'
      path: '/strava/callback'
      fullPath: '/strava/callback'
      preLoaderRoute: typeof StravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strava/login': {
      id: '/strava/login'
      path: '/strava/login'
      fullPath: '/strava/login'
      preLoaderRoute: typeof StravaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StravaCallbackRoute: StravaCallbackRoute,
  StravaLoginRoute: StravaLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
